### ISSUE TITLE
[4.0.0] break's ruby 2.5.9

### ISSUE THREAD

**Issue by tuxmaster5000** [puppetlabs/puppet-lint#121]
RHEL comes with ruby 2.5.9.
But the last update will breaks the app.
```

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:203: syntax error, unexpected ']'                                        
      chunk = code[i..]
                      ^
/usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:233: syntax error, unexpected ']'
...StringScanner.new(code[i + 1..]).scan_until(%r{(\A|[^\\])(\\...
...                              ^
/usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:238: syntax error, unexpected ']'
...StringSlurper.new(code[i + 1..])
...                              ^
/usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:271: syntax error, unexpected ']'
...StringScanner.new(code[i + 1..]).scan_until(%r{(\A|[^\\])(\\...
...                              ^
/usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:286: syntax error, unexpected ']'
...gSlurper.new(code[i + length..])
...                              ^
/usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint/lexer.rb:298: syntax error, unexpected ']'
...gSlurper.new(code[i + length..])
...                              ^ (SyntaxError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/share/gems/gems/puppet-lint-4.0.0/lib/puppet-lint.rb:8:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/bin/puppet-lint:6:in `<main>'
```

**Comment by chelnak** [comment]
Hello! Thanks for opening this issue.

As of v4, puppet-lint requires a minimum Ruby of 2.7.

I would recommend running a Ruby version manager such as rbenv which will allow you to safely switch versions.

**Comment by tuxmaster5000** [comment]
Hi @chelnak ,
rbenv is an very dangerous idea on an production server, because you will need the whole compiler and devel stuff to build the dependencies. In this case RHEL8  comes with  ruby 2.7 as an option. So the version can be switched via dnf module.
But when you remove the support for an version, please add this to the change log. It will make the life more simpler.

**Comment by chelnak** [comment]
Hello - noted.  The removal of Puppet 6/ Ruby 2.5 support was listed in https://github.com/puppetlabs/puppet-lint/pull/113

I have modified the PR title to be more descriptive. This will appear in the changelog when it is next generated.

4.0 was a major release and with that comes breaking changes. I'd always advise to test on a non-production server to avoid issues like this.
