### ISSUE TITLE
puppet-lint no longer installs on MacOS due to the ruby version bump

### ISSUE THREAD

**Issue by claviola** [puppetlabs/puppet-lint#71]
## Describe the Bug

puppet-lint can no longer be installed on macOS 12.6.1, which comes with `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin21]`.

```
$ gem install puppet-lint -v 3.0.1
	The last version of puppet-lint (= 3.0.1) to support your Ruby & RubyGems was 3.0.1. Try installing it with `gem install puppet-lint -v 3.0.1`
	puppet-lint requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
```

## Expected Behavior

Install/upgrade to the latest version of puppet-lint.

## Steps to Reproduce

`gem install puppet-lint -v 3.0.1`

## Environment
 - Version 3.0.1
 - macOS 12.6.1 (Monterey)

## Additional Context

#50 said that the version would be bumped up to 2.5, and that's what the [commit message](https://github.com/puppetlabs/puppet-lint/pull/50/commits/7f67d8cdb30ddc6efef9333c11e49a530197cee3) says, but the version ended up being bumped to [2.7](https://github.com/puppetlabs/puppet-lint/pull/50/commits/7f67d8cdb30ddc6efef9333c11e49a530197cee3#diff-3012ca4021d166a4a26cd8f150eb044acd96bec1409424b8e0665ed9111590f3R34).

**Comment by ekohl** [comment]
Ruby 2.6 is end of life since 2022-04-12 according to https://www.ruby-lang.org/en/downloads/branches/ so I think that was why 2.7 was chosen.

**Comment by claviola** [comment]
That makes sense, but it's a pretty big jump in requirements and breaks a major OS, so if it doesn't directly impact puppet-lint itself it'd be nice to have it rolled back to it at least (not even 2.5 as the PR states.)

**Comment by chelnak** [comment]
@claviola Ruby requirement has been dropped again in #87 .

There will be a 3.1 release in the next couple of days that will sort this out.

**Comment by claviola** [comment]
@chelnak since https://github.com/puppetlabs/puppet-lint/pull/113 by @GSPatton was merged shortly afterwards, I don't think there's been any release past v3.4.0 that can be installed using MacOS's default Ruby.

If there's no hard requirement of Ruby >= 2.7, can this please be reverted?

**Comment by chelnak** [comment]
Hey @claviola! I'll pass this on to @davidsandilands who can talk to the team about it (I no longer work for Puppet 🙂)!
